mediamis/apps/friendlib/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.models import User

from friendlib.models import Book, MediaRequest, DVD, BoardGame
from friendlib.views import *
from friendlib.views import home, search, myaccount
from friendlib.views import mediarequest_set_accepted, mediarequest_set_declined,\
    mediarequest_set_borrowed, mediarequest_set_returned

from friendlib.views import MediaRequestCreateView, MediaRequestDetailView
from friendlib.views import BookCreateView, BookDetailView, BookUpdateView, BookDeleteView
from friendlib.views import DVDCreateView
from friendlib.views import BoardGameCreateView
from friendlib.forms import MediaRequestForm
from friendlib.forms import MediaRequestAcceptForm, BookForm
from django.views.generic import DetailView, UpdateView

urlpatterns = patterns('',
    url(r'^$', home, name="home"),
    url(r'^search/$', search, name="search"),
    url(r'^account/$', myaccount, name="user_home"),
    url(r'^account/medias$', user_medias, name="user_medias"),
    url(r'^account/requests/incoming', user_requests_incoming, name="user_requests_incoming"),
    url(r'^account/requests/outgoing', user_requests_outgoing, name="user_requests_outgoing"),

    url(r'requestmedia/(?P<mediaid>[0-9]+)/$',
        MediaRequestCreateView.as_view(model=MediaRequest,
                           form_class=MediaRequestForm,
                           template_name='friendlib/private/mediarequest_create.html'),
        name='mediarequest_create'),
    url(r'request/(?P<slug>[0-9]+)/$',
        MediaRequestDetailView.as_view(model=MediaRequest,
                                       slug_field='id',
                                       template_name='friendlib/private/mediarequest_detail.html'),
        name='mediarequest_detail'
    ),
    url(r'request/(?P<reqid>[0-9]+)/accept/$', mediarequest_set_accepted, name='mediarequest_accept'),
    url(r'request/(?P<reqid>[0-9]+)/decline/$', mediarequest_set_declined, name='mediarequest_decline'),
    url(r'request/(?P<reqid>[0-9]+)/borrow/$', mediarequest_set_borrowed, name='mediarequest_borrow'),
    url(r'request/(?P<reqid>[0-9]+)/return/$', mediarequest_set_returned, name='mediarequest_return'),

    url(r'^users/(?P<slug>[a-zA-Z]+)/$',
        DetailView.as_view(model=User,
                           slug_field='username',
                           template_name='friendlib/user/user_detail.html'),
        name='user_detail'),
    url(r'^users/(?P<slug>[a-zA-Z]+)/edit$',
        UpdateView.as_view(model=User,
                           slug_field='username',
                           success_url='./',
                           template_name='friendlib/user/user_edit.html'),
        name='user_update'),


    url(r'^books/create/$',
        BookCreateView.as_view(model=Book,
                               form_class=BookForm,
                               template_name='friendlib/media/book/book_create.html'),
        name='book_create'),
    url(r'^books/websearch/$', book_websearch, name='book_websearch'),
    url(r'^books/websearch/(?P<web_id>[a-zA-Z0-9-_]+)/$', book_websearch_detail, name='book_websearch_detail'),

    url(r'^books/(?P<pk>[0-9]+)/$',
        BookDetailView.as_view(model=Book,
                               template_name='friendlib/media/book/book_detail.html'),
        name='book_detail'),
    url(r'^books/(?P<pk>[0-9]+)/edit/$',
        BookUpdateView.as_view(model=Book,
                               form_class=BookForm,
                               template_name='friendlib/media/book/book_edit.html'),
        name='book_update'),
    url(r'^books/(?P<pk>[0-9]+)/delete/$',
        BookDeleteView.as_view(model=Book,
                               template_name='friendlib/media/book/book_confirm_delete.html',
                               success_url='/friendlib/account'),
        name='book_delete'),

    url(r'^dvds/create/$', DVDCreateView.as_view(model=DVD), name='dvd_create'),

    url(r'^boardgame/create/$', BoardGameCreateView.as_view(model=BoardGame), name='boardgame_create'),

)

mediamis/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myfriendlylibrary.views.home', name='home'),
    url(r'^friendlib/', include('friendlib.urls')),
    url(r'^accounts/',  include('registration.urls', namespace='registration', app_name='registration')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.RUN_MODE == 'dev':
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            dict(
                document_root = settings.MEDIA_ROOT,
                show_indexes = True
            )
        ),
        url(r'^specs/(?P<path>.*)$',
            'django.views.static.serve',
            dict(
                document_root = '../specs/',
                show_indexes = True
            )
        ),
        url(r'gbooks/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root':'C:\Users\steph\Docs perso\Code\dev\perso\mediamis\data\google books',
            'show_indexes': True
        }),

    )
else:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            dict(
                document_root = settings.STATIC_ROOT,
                show_indexes = True
            )
        )
    )
    pass
#urlpatterns += patterns('',
#(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
#)

mediamis/apps/friendlib/models.py
# -*- coding: latin-1 -*-
import os
import random
import string

from django.contrib.auth.models import User
from django.core import urlresolvers
from django.db import models
from django.utils.html import escape
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe, mark_for_escaping
from django.template.defaultfilters import slugify
from django.conf import settings

from djeneralize.models import BaseGeneralizationModel
from storages.backends.ftp import FTPStorage
fs = FTPStorage(base_url=settings.REMOTE_MEDIA_URL)

def get_upload_path(book, filename='dummy'):
    #path = os.path.join('upload','medias')
    path = 'upload/medias'  # From windows, we upload on a unix machine ...

    # Make it unique
    unique = string.join(random.sample(string.letters + string.digits, 8), '')

    name = u'book_%s_%s.png' % (slugify(book.title[:10]), unique)
    return os.path.join(path, name)

class Media(BaseGeneralizationModel):
    title = models.CharField(_('title'), max_length=255)
    description = models.TextField(_('description'), blank=True)
    thumbnail = models.ImageField(_('thumbnail'), upload_to=get_upload_path, blank=True, null=True,
                                  default=None, storage=fs)
    
    owner = models.ForeignKey(User, related_name='owned_medias')
    borrower = models.ForeignKey(User, related_name='borrowed_medias',
                                 blank=True, null=True, default=None)
    borrowed = models.BooleanField(_('borrowed'), default=False)

    def __unicode__(self):
        return u'%s' % self.title

    @models.permalink
    def get_absolute_url(self):
        return self.get_as_specialization().get_absolute_url

    @property
    def get_detail_url(self):
        url = '#'
        try:
            url = self.get_as_specialization().get_detail_url
        except:
            pass
        return url
    
    @property
    def get_update_url(self):
        url = '#'
        try:
            url = self.get_as_specialization().get_update_url
        except:
            pass
        return url

    @property
    def get_delete_url(self):
        url = '#'
        try:
            url = self.get_as_specialization().get_delete_url
        except:
            pass
        return url

    @property
    def borrowed_status(self):
        status = u"At home"
        if self.borrowed:
            status = u"Borrowed"

        return status

    @property
    def default_thumbnail(self):
        return self.get_as_specialization().default_thumbnail

    @property
    def html_link(self):
        html = u'<a href="%s" class="btn-link">%s</a>' % (
            self.get_detail_url,
            self.title.capitalize())
        return mark_safe(html)

    def get_html_picture(self, small=False):
        if not self.thumbnail.name:
            # Init default ...
            self.thumbnail.name = self.default_thumbnail
            self.save()

        css_class = "media-thumb-norm"
        if small:
            css_class = "media-thumb-small"

        html = u'<a href="%s"><img src="%s" class="%s"></a>' % (
            self.get_detail_url,
            self.thumbnail.url,
            css_class)
        return mark_safe(html)

    @property
    def html_thumbnail_small(self):
        return self.get_html_picture(small=True)

    @property
    def html_thumbnail(self):
        return self.get_html_picture(small=False)

class Book(Media):
    author = models.CharField(_('author name'), max_length=255, null=True, blank=True)
    size = models.CharField(_('size of the book'), max_length=255, null=True, blank=True)
    nb_pages = models.PositiveIntegerField(_('number of pages'), null=True, blank=True)

    class Meta:
        specialization = 'book'

    def __unicode__(self):
        return u'%s' % self.title

    @models.permalink
    def get_absolute_url(self):
        return ('book_detail', [self.pk,])

    @property
    def get_detail_url(self):
        return urlresolvers.reverse('book_detail', args=[self.pk])
    
    @property
    def get_update_url(self):
        return urlresolvers.reverse('book_update', args=[self.pk])

    @property
    def get_delete_url(self):
        return urlresolvers.reverse('book_delete', args=[self.pk])

    @property
    def shortDetails(self):
        return self.description

    @property
    def default_thumbnail(self):
        return u'img/book_default.jpg'

class Movie(Media):
    allocine_id = models.PositiveIntegerField(_('allocine id'), null=True, blank=True)

    class Meta:
        specialization = 'movie'

    def __unicode__(self):
        return u'%s' % self.title

    @property
    def shortDetails(self):
        return self.synopsis

    @property
    def default_thumbnail(self):
        return u'img/dvd_default.jpg'

class DVD(Movie):
    number_of_disc = models.PositiveSmallIntegerField(_('number of disc'), null=True, blank=True)

    class Meta:
        specialization = 'dwd'
        
    @models.permalink
    def get_absolute_url(self):
        return ('user_home',)

    @property
    def get_update_url(self):
        return urlresolvers.reverse('user_home',)

    @property
    def get_delete_url(self):
        return urlresolvers.reverse('user_home',)

class Divx(Movie):
    QUALITY_CHOICES = (
        (u'G', _('Good')),
        (u'B', _('Bad')),
    )
    
    quality = models.CharField(_('quality'), max_length=1, blank=True,
                               choices = QUALITY_CHOICES)

    class Meta:
        specialization = 'divx'

    @models.permalink
    def get_absolute_url(self):
        return ('user_home',)

    @property
    def get_update_url(self):
        return urlresolvers.reverse('user_home',)

    @property
    def get_delete_url(self):
        return urlresolvers.reverse('user_home',)

    
class BoardGame(Media):
    number_players = models.PositiveSmallIntegerField(_('number of player'), null=True, blank=True)

    class Meta:
        specialization = 'boardgame'

    @models.permalink
    def get_absolute_url(self):
        return ('user_home',)

    @property
    def get_update_url(self):
        return urlresolvers.reverse('user_home',)

    @property
    def get_delete_url(self):
        return urlresolvers.reverse('user_home',)

    @property
    def default_thumbnail(self):
        return u'img/boardgame_default.jpg'

class MediaRequest(models.Model):
    """ Symbolize the request of one user to catch another user's Media
    Could have different status:
        - (P) Pending
        - (D) Declined
        - (A) Accepted but not borrowed yet
        - (B) Accepted and currently borrowed
        - (R) Accepted, borrowed and returned back

    TODO: If status is Accepted, Media status need to be set as "borrowed"
    """
    STATUS_CHOICES = (
        (u'P', _('Pending')),
        (u'D', _('Declined')),
        (u'A', _('Accepted but not borrowed yet')),
        (u'B', _('Currently borrowed')),
        (u'R', _('Returned'))
    )

    media = models.ForeignKey(Media, related_name='requests', blank=False, null=False)
    borrower = models.ForeignKey(User, related_name='requested_medias', blank=False, null=False)
    message = models.TextField()
    status = models.CharField(_('status'), max_length=1, blank=False,
                               choices = STATUS_CHOICES)
    date_status_updated = models.DateTimeField(auto_now=True, )    # Last update of the request
    date_requested = models.DateTimeField(auto_now_add=True)     # Creation of the request
    date_answered = models.DateTimeField(null=True, blank=True)      # When the owner answered yes or no
    date_media_rented = models.DateTimeField(null=True, blank=True)  # (set by owner) When the media could be rented
    date_return_due = models.DateTimeField(null=True, blank=True)    # (set by owner) When the Media has to be returned

    def __unicode__(self):
        label = u'Error in the status ...'
        if self.status == 'P':
            label = u'%s asks to borrow <%s> from %s' % (
                self.borrower.__unicode__().capitalize(),
                self.media,
                self.media.owner.__unicode__().capitalize())
        elif self.status == 'D':
            label = u'%s has denied <%s> from %s' % (
                self.media.owner.__unicode__().capitalize(),
                self.media,
                self.borrower.__unicode__().capitalize())
        elif self.status == 'A':
            label = u'%s has accepted to borrow <%s> to %s, but not borrowed yet' % (
                self.media.owner.__unicode__().capitalize(),
                self.media,
                self.borrower.__unicode__().capitalize())
        elif self.status == 'B':
            label = u'%s is currently borrowing <%s> from %s' % (
                self.borrower.__unicode__().capitalize(),
                self.media,
                self.media.owner.__unicode__().capitalize())
        elif self.status == 'R':
            label = u'%s has returned <%s> to %s' % (
                self.borrower.__unicode__().capitalize(),
                self.media,
                self.media.owner.__unicode__().capitalize())

        return escape(label)

    @property
    def owner_short_status(self):
        status = self.__unicode__()
        if self.status == 'P':
            status = u'%s asked to borrow' % self.borrower.__unicode__().capitalize()
        elif self.status == 'D':
            status = u'You declined.'
        elif self.status == 'A':
            status = u'You accepted.'
        elif self.status == 'B':
            status = u'You actually borrow it'
        elif self.status == 'R':
            status = u'%s returned it to you' % self.borrower.__unicode__().capitalize()
        return status

    @property
    def borrower_short_status(self):
        status = self.__unicode__()
        if self.status == 'P':
            status = u'You ask to borrow'
        elif self.status == 'D':
            status = u'Your request was denied'

mediamis/apps/friendlib/templates/friendlib/media/book/book_confirm_delete.html
{% extends "friendlib/media/media_confirm_delete.html" %}
{% load i18n %}

{% block media_confirm %}
	<form method="POST">{% csrf_token %}
		<h2>{% trans "You sure to delete ?!" %}</h2>
		{{ form.as_p }}

		<input class="btn btn-danger" type="submit" value="{% trans "Yes" %}" />
	</form>
{% endblock media_confirm %}

mediamis/apps/friendlib/templates/friendlib/media/book/book_create.html
{% extends "friendlib/media/media_create.html" %}
{% load i18n %}

{% block media_create %}
    <legend>{% trans "Create new book" %}</legend>

    <form id="websearch" class="form-search" method="GET" action="{% url book_websearch %}">{% csrf_token %}
        <label>Search a book on internet ...</label>

        <input id="query" type="text">
        <a id="go" class="btn">Search</a>
    </form>

    <div id="websearch_result"></div>

    <hr>
	<form enctype="multipart/form-data" class="form-horizontal" method="POST" action="{% url book_create %}">{% csrf_token %}
        <legend>Edit</legend>
        <div id="load"></div>
        <div id="fields">
        {% include "friendlib/snippets/media_form_field.html" with field=form.title %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.description %}

        <img id="thumbnail_preview" src=""/>
        {% with field=form.thumbnail %}
            {% if field.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}

                <label class="control-label">{{ field.label }}</label>
                <div class="controls">
                    <input type="radio" name="thumbnail_type" value="url"><input name="thumbnail_url" id="id_thumbnail_url" type="text"><br>
                    <input type="radio" name="thumbnail_type" value="local">{{ field }}

                {% if field.errors %}
                    {% for error in field.errors %}
                    <span class="help-inline">{{ error }}</span>
                    {% endfor %}
                {% endif %}

                </div>
            </div>
        {% endwith %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.author %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.size %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.nb_pages %}
        </div>

    
        {# Hidden fields #}
        {{ form.specialization_type }}
        {{ form.owner }}
		<input class="btn btn-primary" type="submit" value="{% trans "Create" %}" />
	</form>
{% endblock media_create %}

{% block js %}
    $.fn.spin = function(opts) {
      this.each(function() {
        var $this = $(this),
            data = $this.data();

        if (data.spinner) {
          data.spinner.stop();
          delete data.spinner;
        }
        if (opts !== false) {
          data.spinner = new Spinner($.extend({color: $this.css('color')}, opts)).spin(this);
        }
      });
      return this;
    };

    var opts = {
      lines: 13, // The number of lines to draw
      length: 7, // The length of each line
      width: 4, // The line thickness
      radius: 10, // The radius of the inner circle
      corners: 1, // Corner roundness (0..1)
      rotate: 0, // The rotation offset
      color: '#000', // #rgb or #rrggbb
      speed: 1, // Rounds per second
      trail: 60, // Afterglow percentage
      shadow: false, // Whether to render a shadow
      hwaccel: false, // Whether to use hardware acceleration
      className: 'spinner', // The CSS class to assign to the spinner
      zIndex: 2e9, // The z-index (defaults to 2000000000)
      top: 'auto', // Top position relative to parent in px
      left: 'auto' // Left position relative to parent in px
    };

    $.ajaxSetup({
        timeout: 5000,
        error: function(event, request, settings){
            alert("{% trans "Sorry, an error has occured" %}");
            console.log(event, request, settings);

            $('#load').spin(false);
            $('#fields').removeAttr('style')
            $('#websearch_result').spin(false);

        }
    });

    function websearch(page) {
        page = typeof page !== 'undefined' ? page : 0;

        /* Show loading animation */
        $('#websearch_result').empty().attr('style', 'height:150px');
        $('#websearch_result').spin();

        query = $('#websearch > input#query').val();
        csrf = $('#websearch input[name=csrfmiddlewaretoken]').val();
        console.log("Search with: " + query + ", " + page);
        $('#websearch_result').load(
            '{% url book_websearch %}',
            {
                'action': 'search',
                'query': query,
                'csrfmiddlewaretoken': csrf,
                'page': page
            },
            function (responseText, textStatus, req) {
                $(this).removeAttr('style')
                if (textStatus == "error") {
                    $('#websearch_result').spin(false);
                    $(this).html('<em>{% trans "Sorry, an error has occured" %}</em>');
                    return false;
                }
                m = 'Load was performed with ' + query;

                /* Activate links */
                $('a#load_details').click(function(e) {
                    e.preventDefault();
                    var web_id = $(this).attr('web_id');
                    load_details(web_id);
                });
                $('a#webresult_next, a#webresult_prev').click(function(e) {
                    e.preventDefault();
                    /* Get page number */
                    page = $(this).attr('data-page');
                    websearch(page);
                });
            }
        );
    }
    
    function load_details(web_id) {
        /* Show loading animation */
        $('#load').show().spin();
        $('#fields').css({opacity: '0.7'});


        /* Load infos for this particular book ... */
        base_url = '{% url book_websearch_detail 0 %}'
        url = base_url.replace('/0/', '/'+web_id+'/')

        $.getJSON(
            url,
            function(json, textStatus, jqXHR) {
                console.log(json, textStatus, jqXHR);
                $('#thumbnail_preview').attr('src', json['thumbnail']);
                $('input:radio[name="thumbnail_type"][value="url"]').prop('checked', true);

                $('#id_title').val(json['title']);
                $('#id_description').val(json['description']);
                $('#id_thumbnail_url').val(json['thumbnail']);
                $('#id_author').val(json['authors']);
                $('#id_size').val(json['size']);
                $('#id_nb_pages').val(json['nb_pages']);
                $('#fields').show();
                $('#load').hide();
            }
        ).error(function() {
            $('#load').html('<em>{% trans "Sorry, an error has occured" %}</em>');
        }).complete(function() {
            $('#load').spin(false);
            $('#fields').removeAttr('style')
        });
    };


    $('#websearch > input#query').keypress(function(e) {
        if(e.which == 10 || e.which == 13) {
            event.preventDefault();
            websearch();
       }
    });
    $('#websearch > a#go').click(function() {
        websearch();
    });



{% endblock %}

mediamis/apps/friendlib/templates/friendlib/media/book/book_detail.html
{% extends "friendlib/media/media_detail.html" %}
{% load i18n %}

{% block media_detail %}
                <dl class="">
                    <dt>{% trans "Author" %}</dt>
                    <dd>{{ book.author }}</dd>

                    <dt>Nb de pages</dt>
                    <dd>{{ book.nb_pages }}</dd>

                    <dt>Resume</dt>
                    <dd>{{ book.description|safe }}</dd>
                </dl>
{% endblock %}

mediamis/apps/friendlib/templates/friendlib/media/book/book_edit.html
{% extends "friendlib/media/media_edit.html" %}
{% load i18n %}

{% block media_edit %}
	<form enctype="multipart/form-data" method="POST" action="{% url book_update book.pk %}">{% csrf_token %}
		<h2>{% trans "Edit book" %}</h2>

        {% include "friendlib/snippets/media_form_field.html" with field=form.title %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.description %}

        <img id="thumbnail_preview" src=""/>
        {% with field=form.thumbnail %}
            {% if field.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}

                <label class="control-label">{{ field.label }}</label>
                <div class="controls">
                    <input type="radio" name="thumbnail_type" value="url"><input name="thumbnail_url" id="id_thumbnail_url" type="text"><br>
                    <input type="radio" name="thumbnail_type" value="local">{{ field }}

                {% if field.errors %}
                    {% for error in field.errors %}
                    <span class="help-inline">{{ error }}</span>
                    {% endfor %}
                {% endif %}

                </div>
            </div>
        {% endwith %}
    
        {% include "friendlib/snippets/media_form_field.html" with field=form.author %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.size %}

        {% include "friendlib/snippets/media_form_field.html" with field=form.nb_pages %}


        {# Hidden fields #}
        {{ form.specialization_type }}
        {{ form.owner }}
		<input class="btn btn-success pull-right" type="submit" value="{% trans "Save" %}" />
	</form>


{% endblock media_edit %}